import { PRIVACY_VERSION } from "../src/shared/cbam-navigator";
export function fixture() {
  return {
    application: {
      clientType: "operator",
      serviceType: "verification",
      companyName: "Navigator Test Company",
      contactName: "Test Contact",
      email: "test@example.invalid",
      phone: "000-0000-0000",
      address: "",
      country: "대한민국",
      sites: "시험 사업장",
      verificationYears: ["2026"],
      cbamGoods: ["철강"],
      cnCodes: "73181590",
      operatorCount: "1",
      processCount: "1",
      goodsCount: "1",
      dataLocation: "",
      remoteAccess: "yes",
      managementSystems: [],
      dataPersonnel: "",
      communicationTemplate: "all",
      mmdStatus: "clear",
      carbonPrice: "no",
      previouslyVerified: "no",
      embeddedEmissionsKt: "",
      productionProcesses: "압연",
      fuelStreams: "",
      goodsComplexity: "simple",
      biomass: "none",
      chp: false,
      knownClient: false,
      notes: "Synthetic local test",
      consent: true,
    },
    navigatorData: {
      sessionId: "NAV-12345678-1234-4123-8123-123456789012",
      productName: "철강 볼트",
      searchedCnCodes: ["73181590"],
      readinessAnswers: {},
      evidenceStatus: {},
    },
    marketingConsent: false,
    privacyNoticeVersion: PRIVACY_VERSION,
  };
}
