'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { LEAD_STATUSES, type NavigatorLead, type LeadStatus } from '@/lib/cbam-lead';
import { QUESTIONS, CATEGORY_LABELS, scoreReadiness } from '@/lib/cbam-navigator';
const answerLabels = { ready:'준비됨', partial:'일부 준비', missing:'미준비 / 모름' };
const evidenceLabels = { ready:'준비 완료', partial:'일부 준비', missing:'미준비', not_applicable:'해당 없음 (근거 확인 필요)' };
const time = (value?: string) => value ? new Date(value).toLocaleString('ko-KR') : '-';
export default function NavigatorLeads() {
  const [leads,setLeads] = useState<NavigatorLead[]>([]), [selected,setSelected] = useState<NavigatorLead | null>(null);
  const [loading,setLoading] = useState(true), [error,setError] = useState(''), [saving,setSaving] = useState(false), [notice,setNotice] = useState('');
  const [query,setQuery] = useState(''), [consultationOnly,setConsultationOnly] = useState(false), [statusFilter,setStatusFilter] = useState('');
  const [status,setStatus] = useState<LeadStatus>('미연락'), [assignedTo,setAssignedTo] = useState(''), [managementNotes,setManagementNotes] = useState('');
  const select = useCallback((lead: NavigatorLead | null) => { setSelected(lead); setStatus(lead?.status || '미연락'); setAssignedTo(lead?.assignedTo || ''); setManagementNotes(lead?.managementNotes || ''); setNotice(''); },[]);
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { const response = await fetch('/api/cbam/navigator-leads',{ cache:'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.message);
      setLeads(result.leads); const ref = new URLSearchParams(window.location.search).get('lead');
      select(result.leads.find((x: NavigatorLead) => x.reference === (ref || selected?.reference)) || result.leads[0] || null);
    } catch(e) { setError(e instanceof Error ? e.message : '접수를 불러오지 못했습니다.'); } finally { setLoading(false); }
  },[select,selected?.reference]);
  useEffect(() => { load(); },[]); // eslint-disable-line react-hooks/exhaustive-deps
  const visible = useMemo(() => leads.filter(x => (!consultationOnly || x.consultationRequestedAt) && (!statusFilter || x.status === statusFilter) && `${x.reference} ${x.companyName} ${x.contactName} ${x.email} ${x.phone}`.toLowerCase().includes(query.toLowerCase())),[leads,query,consultationOnly,statusFilter]);
  async function save(retry = false) {
    if (!selected) return; setSaving(true); setError(''); setNotice('');
    try { const response = await fetch('/api/cbam/navigator-leads',{ method:'PUT',headers:{ 'Content-Type':'application/json' },body:JSON.stringify({ reference:selected.reference, ...(retry ? { action:'retry-notification' } : { status,assignedTo,managementNotes }) }) });
      const result = await response.json(); if (!response.ok) throw new Error(result.message);
      const next = retry ? result.leads.find((x: NavigatorLead) => x.reference === selected.reference) : result.lead;
      setLeads(current => retry ? result.leads : current.map(x => x.reference === next.reference ? next : x)); select(next); setNotice(retry ? '알림 재전송 요청을 처리했습니다. 아래 알림 상태를 확인해 주세요.' : '관리 내용을 저장했습니다.');
    } catch(e) { setError(e instanceof Error ? e.message : '저장하지 못했습니다.'); } finally { setSaving(false); }
  }
  const scored = selected ? scoreReadiness(selected.navigatorData.readinessAnswers || {}) : null;
  return <section aria-label="Navigator 진단 접수">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-black">Navigator 진단 접수</h2><p className="mt-1 text-sm text-slate-500">문서 요청 {leads.filter(x => x.documents.length).length}건 · 상담 요청 {leads.filter(x => x.consultationRequestedAt).length}건 · 미연락 상담 {leads.filter(x => x.consultationRequestedAt && x.status === '미연락').length}건</p></div><button onClick={load} disabled={loading} className="rounded-lg border bg-white px-4 py-2 text-sm font-bold">새로고침</button></div>
    {error && <p role="alert" className="mb-4 rounded-xl bg-amber-50 p-4 text-amber-900">{error}</p>}
    <div className="mb-5 flex flex-wrap gap-3"><input aria-label="업체·담당자 검색" placeholder="회사명, 담당자, 이메일, 전화번호 검색" value={query} onChange={e => setQuery(e.target.value)} className="min-w-0 flex-1 rounded-lg border px-3 py-2" /><select aria-label="처리상태 필터" value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="rounded-lg border px-3 py-2"><option value="">전체 상태</option>{LEAD_STATUSES.map(x => <option key={x}>{x}</option>)}</select><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={consultationOnly} onChange={e => setConsultationOnly(e.target.checked)} />상담 요청만</label></div>
    <div className="grid items-start gap-6 xl:grid-cols-[1.1fr_.9fr]">
      <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[740px] text-left text-sm"><thead className="bg-slate-100 text-xs text-slate-600"><tr>{['접수일 / 번호','회사 / 담당자','연락처','요청 종류','준비도','처리상태'].map(x => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{visible.map(lead => { const score = scoreReadiness(lead.navigatorData.readinessAnswers || {}); return <tr key={lead.reference} className={`cursor-pointer border-t hover:bg-teal-50 ${selected?.reference === lead.reference ? 'bg-teal-50' : ''}`} onClick={() => select(lead)}><td className="p-3"><span className="block text-xs">{time(lead.createdAt)}</span><button className="mt-1 break-all text-left text-xs font-bold" onClick={() => select(lead)}>{lead.reference}</button></td><td className="p-3"><strong className="block">{lead.companyName}</strong>{lead.contactName}</td><td className="p-3"><span className="block">{lead.phone}</span><span className="break-all text-xs">{lead.email}</span></td><td className="p-3">{lead.consultationRequestedAt && <strong className="block text-teal-700">상담 요청</strong>}{lead.documents.length > 0 && <span className="text-xs">문서: {lead.documents.join(', ').toUpperCase()}</span>}{lead.applicationReference && <span className="block text-xs">정식 신청 연결</span>}</td><td className="p-3">{score.complete ? `${score.readinessScore}%` : `${score.answered}/24 응답`}</td><td className="p-3">{lead.status}</td></tr>; })}{!visible.length && <tr><td colSpan={6} className="p-10 text-center text-slate-500">{loading ? '불러오는 중…' : '조건에 맞는 진단 접수가 없습니다.'}</td></tr>}</tbody></table></div>
      {selected && scored ? <aside className="space-y-5">
        <div className="rounded-2xl border bg-white p-5 shadow-sm"><p className="break-all text-xs font-bold text-teal-700">{selected.reference}</p><h3 className="mt-2 text-xl font-black">{selected.companyName}</h3><p className="mt-2">담당자: {selected.contactName}</p><p><a className="text-teal-700 underline" href={`tel:${selected.phone}`}>{selected.phone}</a> · <a className="break-all text-teal-700 underline" href={`mailto:${selected.email}`}>{selected.email}</a></p><p className="mt-3 text-xs text-slate-500">최초 접수: {time(selected.createdAt)}<br />마지막 갱신: {time(selected.updatedAt)}<br />동의: {time(selected.consentedAt)} / 안내 버전 {selected.privacyNoticeVersion}</p>
          <div className="mt-4 rounded-xl bg-teal-50 p-4 text-sm"><strong>{selected.consultationRequestedAt ? '진단 결과 상담 요청' : '문서 요청 접수'}</strong><p className="mt-1 whitespace-pre-wrap">{selected.consultationMessage || (selected.consultationRequestedAt ? '별도 상담 내용 없음' : '상담을 요청하지 않은 문서 요청 건입니다.')}</p>{selected.consultationRequestedAt && <p className="mt-3 text-xs">상담 접수: {time(selected.consultationRequestedAt)}<br />이메일 알림: {selected.notificationStatus === 'requested' ? '알림 전달 요청 완료 (메일 수신은 별도 확인)' : selected.notificationStatus === 'sending' ? '알림 전달 중' : selected.notificationStatus === 'failed' ? '전달 실패 - 재전송 가능' : '미요청'}</p>}{selected.notificationStatus === 'failed' && <button type="button" disabled={saving} onClick={() => save(true)} className="mt-3 rounded-lg border border-teal-600 px-3 py-2 font-bold">상담 알림 재전송</button>}</div>
          {selected.applicationReference && <p className="mt-3 text-sm">연결 신청: <Link className="text-teal-700 underline" href="/cbam/admin">{selected.applicationReference}</Link></p>}
          <div className="mt-5 space-y-3"><label className="block text-sm font-bold">처리상태<select value={status} onChange={e => setStatus(e.target.value as LeadStatus)} className="mt-1 w-full rounded-lg border p-2">{LEAD_STATUSES.map(x => <option key={x}>{x}</option>)}</select></label><label className="block text-sm font-bold">내부 담당자<input maxLength={120} value={assignedTo} onChange={e => setAssignedTo(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-bold">관리 메모<textarea rows={4} maxLength={3000} value={managementNotes} onChange={e => setManagementNotes(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><button type="button" disabled={saving} onClick={() => save()} className="w-full rounded-lg bg-slate-950 px-4 py-3 font-bold text-white">{saving ? '저장 중…' : '관리 내용 저장'}</button>{notice && <p role="status" className="text-sm text-teal-700">{notice}</p>}</div>
        </div>
        <div className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-black">진단 및 요청사항</h3><dl className="mt-3 space-y-2 text-sm">{[['제품',selected.navigatorData.productName],['CN 코드',selected.navigatorData.searchedCnCodes?.join(', ')],['사업장',selected.sites],['생산공정',selected.productionProcesses],['생산경로',selected.productionRoute],['전구물질',selected.precursors],['보고 대상·수신 부서',selected.recipient],['자료 대상기간',selected.reportingPeriod],['회신 요청기한',selected.deadline],['지원·의사결정 요청',selected.decisionRequest]].map(([label,value]) => <div key={label}><dt className="text-xs text-slate-500">{label}</dt><dd className="whitespace-pre-wrap break-words">{value || '미입력'}</dd></div>)}</dl><p className="mt-4 text-sm font-bold">자가진단 준비도: {scored.complete ? `${scored.readinessScore}%` : `진단 미완료 (${scored.answered}/24)`}</p><details className="mt-4 text-sm"><summary className="cursor-pointer font-bold">전체 24개 진단·증빙 상태 보기</summary><ul className="mt-3 space-y-3">{QUESTIONS.map(q => <li key={q.id} className="border-t pt-3"><strong>{q.id} · {CATEGORY_LABELS[q.category]}</strong><p>{q.text}</p><p className="mt-1 text-xs text-slate-500">자가진단: {answerLabels[selected.navigatorData.readinessAnswers?.[q.id] as keyof typeof answerLabels] || '미응답'}<br />{q.evidence}: {evidenceLabels[selected.navigatorData.evidenceStatus?.[q.id] as keyof typeof evidenceLabels] || '확인 전'}</p></li>)}</ul></details></div>
      </aside> : <div className="rounded-2xl border border-dashed bg-white p-10 text-center text-slate-500">진단 접수를 선택해 주세요.</div>}
    </div>
  </section>;
}
