import type { SamAccount, SamBilingualText } from '@/lib/samTypes';

const bilingual = (ko: string, en: string, approved = true): SamBilingualText => ({
  ko,
  en,
  status: approved ? 'approved' : 'review',
});

const now = '2026-08-03T00:00:00.000Z';
const commonTeam = [
  { id: 'team-sam', role: bilingual('한국 SAM', 'SAM Korea'), name: 'Dal' },
  { id: 'team-sponsor', role: bilingual('총괄 Sponsor', 'Executive Sponsor'), name: 'Ryan' },
  { id: 'team-technical', role: bilingual('기술 리드', 'Technical Lead'), name: 'CSY / TKK' },
  { id: 'team-escalation', role: bilingual('이슈 대응', 'Escalation'), name: 'Ryan / BGL' },
];

const base = (input: Partial<SamAccount> & Pick<SamAccount, 'id' | 'name' | 'sector'>): SamAccount => ({
  country: 'Korea', manager: 'Dal',
  internalSponsor: bilingual('Ryan(라인 매니저), CSY/BGL/TKK(심사 수행 지원)', 'Ryan (Line Manager); CSY / BGL / TKK (Audit Delivery Support)'),
  clientSponsor: bilingual('', '', false), lastQbrDate: '', qbrOutcome: bilingual('', '', false),
  nextQbrDate: '', lastVisitDate: '', attendees: bilingual('Dal', 'Dal'),
  visitOutcome: bilingual('', '', false), opportunity: bilingual('', '', false),
  dealStage: bilingual('진행 중', 'In delivery'), estimatedCloseDate: '', dealValueUsd: 0,
  dealValueNote: bilingual('', '', false), atRisk: false, risk: bilingual('', '', false),
  growthStrategy: bilingual('', '', false), crossSell: bilingual('', '', false),
  notes: bilingual('', '', false), reviewCadence: 'biweekly', nextReviewDate: '',
  affiliates: [], manualSalesRecordIds: [], contacts: [],
  team: commonTeam.map((member) => ({ ...member, role: { ...member.role } })),
  actions: [], updates: [], createdAt: now, updatedAt: now, createdBy: 'seed', updatedBy: 'seed',
  ...input,
});

export const initialSamAccounts = (): SamAccount[] => [
  base({
    id: 'sam-hyundai', name: bilingual('현대자동차그룹', 'Hyundai Motor Group'),
    sector: bilingual('운송 및 모빌리티', 'Transportation & Mobility'),
    clientSponsor: bilingual('현대차 탄소중립추진팀 이승훈 책임, 공급망지속경영팀 정예민 책임, 기아 탄소중립전략팀 김한별 매니저', 'Lee Seung-hoon, Hyundai Carbon Neutrality Promotion; Jung Ye-min, Supply Chain Sustainability; Kim Han-byeol, Kia Carbon Neutrality Strategy'),
    lastQbrDate: '2026-06-16',
    qbrOutcome: bilingual('현대 글로벌 권역본부 온실가스 검증 결과를 보고하고 현대·기아 협력사 감축계획 평가 워크숍을 진행함.', 'Reported Hyundai global regional HQ GHG verification results and conducted a Hyundai/Kia supplier reduction assessment workshop.'),
    nextQbrDate: '2026-08-18', lastVisitDate: '2026-06-16',
    attendees: bilingual('Dal, CSY, TKK, EJK, Ryan', 'Dal, CSY, TKK, EJK, Ryan'),
    visitOutcome: bilingual('현대·기아의 검증 및 공급망 탈탄소 후속 기회를 확인함.', 'Confirmed follow-up opportunities for Hyundai/Kia assurance and supplier decarbonisation.'),
    opportunity: bilingual('현대 글로벌 권역본부 GHG 검증, 현대·기아 협력사 감축 평가, 기아 사업장 GHG 검증', 'Hyundai Global HQ GHG Verification; Hyundai/Kia Supplier GHG Reduction Assessment; Kia Site GHG Verification'),
    dealStage: bilingual('현재 과업 수행 및 확장 논의', 'Current delivery and expansion discussion'),
    dealValueUsd: 265000, dealValueNote: bilingual('약 3.6억원, 환율 변동 가능', 'Approx. KRW 360m, subject to FX'),
    risk: bilingual('현재 수행은 정상이지만 2027년 갱신은 보장되지 않아 선제적 관계 관리가 필요함.', 'Current delivery is on track, but 2027 renewal is not guaranteed and requires proactive engagement.'),
    growthStrategy: bilingual('2027년 현대·기아 GHG 검증 갱신을 확보하고 공급망 탈탄소 및 ESG assurance로 확장한다.', 'Secure 2027 Hyundai/Kia GHG verification renewal and expand into supplier decarbonisation and ESG assurance.'),
    crossSell: bilingual('Scope 3, CBAM, EU 배터리 규정, LCA/PCF 및 기후공시 대응', 'Scope 3, CBAM, EU Battery Regulation, LCA/PCF and climate disclosure readiness'),
    notes: bilingual('LRQA Korea 지속가능성 서비스의 핵심 전략 고객', 'Priority strategic sustainability account for LRQA Korea'),
    affiliates: [
      { id: 'hyundai-1', nameKo: '현대자동차', nameEn: 'Hyundai Motor Company', aliases: ['현대차', 'Hyundai Motors Company', 'Hyundai Motors Company Group'] },
      { id: 'hyundai-2', nameKo: '기아', nameEn: 'Kia Corporation', aliases: ['기아자동차', 'Kia'] },
      { id: 'hyundai-3', nameKo: '현대모비스', nameEn: 'Hyundai Mobis', aliases: [] },
      { id: 'hyundai-4', nameKo: '현대글로비스', nameEn: 'Hyundai Glovis', aliases: [] },
      { id: 'hyundai-5', nameKo: '현대제철', nameEn: 'Hyundai Steel', aliases: [] },
      { id: 'hyundai-6', nameKo: '현대엔지니어링', nameEn: 'Hyundai Engineering', aliases: [] },
    ],
  }),
  base({
    id: 'sam-samsung', name: bilingual('삼성그룹', 'Samsung Group'),
    sector: bilingual('건설 및 제조', 'Construction & Manufacturing'),
    clientSponsor: bilingual('삼성 지속가능성, EHS, 품질 및 구매 부문의 주요 담당자', 'Key Samsung stakeholders across sustainability, EHS, quality and procurement'),
    lastQbrDate: '2026-02-01',
    qbrOutcome: bilingual('삼성전자 휴대폰·태블릿·PC 등 완제품 LCA 검증을 지속하고 계열사 확장을 논의함.', 'Continued finished-product LCA verification for Samsung Electronics and discussed affiliate expansion.'),
    nextQbrDate: '2026-09-15',
    opportunity: bilingual('삼성전자 완제품 LCA 검증 및 삼성 계열사 기후·ISO 서비스', 'Samsung Electronics Finished Product LCA Verification and Samsung Affiliate Climate/ISO Services'),
    dealStage: bilingual('LCA 수행 및 확장 논의', 'LCA delivery and expansion discussion'),
    dealValueUsd: 230000, dealValueNote: bilingual('예상 범위 USD 190k~270k', 'Estimated range USD 190k-270k'),
    risk: bilingual('제품 수량과 제품별 계약 지속성을 모니터링해야 함.', 'Monitor product volume and product-by-product contract continuity.'),
    growthStrategy: bilingual('삼성전자 완제품 LCA 검증을 유지·확대하고 계열사 지속가능성 서비스로 확장한다.', 'Protect and expand Samsung Electronics finished-product LCA verification and grow affiliate sustainability services.'),
    crossSell: bilingual('제품 탄소발자국, Scope 3, 공급망 데이터 검증, ESG assurance', 'Product carbon footprint, Scope 3, supplier data assurance and ESG assurance'),
    notes: bilingual('제품별 하도급 구조이므로 제품 파이프라인을 조기에 파악해야 함.', 'Product-by-product subcontracting requires early product pipeline visibility.'),
    affiliates: [
      { id: 'samsung-1', nameKo: '삼성전자', nameEn: 'Samsung Electronics', aliases: [] },
      { id: 'samsung-2', nameKo: '삼성SDI', nameEn: 'Samsung SDI', aliases: [] },
      { id: 'samsung-3', nameKo: '삼성물산', nameEn: 'Samsung C&T', aliases: ['Samsung C and T'] },
    ],
  }),
  base({
    id: 'sam-posco', name: bilingual('포스코', 'POSCO'), sector: bilingual('건설 및 제조', 'Construction & Manufacturing'),
    clientSponsor: bilingual('지속가능성, 기후변화, EHS, 품질 및 EU 수출 부문 Sponsor 발굴 필요', 'Target sponsors across sustainability, climate, EHS, quality and EU export functions'),
    qbrOutcome: bilingual('20년 이상 ISO 14001 고객이었으나 비용 압박으로 저가 인증기관으로 전환함.', 'Former ISO 14001 client of more than 20 years that moved to a lower-cost certification body.'),
    opportunity: bilingual('철강 제품 EU CBAM, 기후변화 및 ISO 재유치', 'EU CBAM for steel products, climate change and ISO win-back'),
    dealStage: bilingual('재접근 및 타겟 영업', 'Re-engagement and targeted prospecting'),
    estimatedCloseDate: '2027-06-30', atRisk: true,
    risk: bilingual('장기 고객을 잃은 상태로 Sponsor와 관계를 다시 구축해야 함.', 'Strategic win-back account requiring sponsor identification and relationship rebuilding.'),
    growthStrategy: bilingual('EU CBAM과 기후변화 기술 신뢰도를 중심으로 관계를 회복하고 선택적으로 ISO 재진입을 추진한다.', 'Rebuild the relationship through EU CBAM and climate expertise and selectively pursue ISO re-entry.'),
    crossSell: bilingual('CBAM, 내재배출 검증, 제품 탄소발자국, GHG assurance', 'CBAM, embedded emissions verification, product carbon footprint and GHG assurance'),
    notes: bilingual('가격 경쟁보다 LRQA의 글로벌 assurance 역량을 강조해야 함.', 'Lead with LRQA global assurance capability rather than price-only competition.'),
    reviewCadence: 'weekly',
    affiliates: [
      { id: 'posco-1', nameKo: '포스코', nameEn: 'POSCO', aliases: ['POSCO Holdings', '포스코홀딩스'] },
      { id: 'posco-2', nameKo: '포스코인터내셔널', nameEn: 'POSCO International', aliases: [] },
      { id: 'posco-3', nameKo: '포스코퓨처엠', nameEn: 'POSCO Future M', aliases: [] },
    ],
  }),
  base({
    id: 'sam-sk', name: bilingual('SK그룹', 'SK Group'), sector: bilingual('에너지·재생에너지·광업', 'Energy, Renewables & Mining'),
    clientSponsor: bilingual('SK하이닉스, SK실트론, SK이노베이션의 지속가능성·기후·EHS 주요 담당자', 'Key sustainability, climate and EHS stakeholders across SK hynix, SK siltron and SK innovation'),
    qbrOutcome: bilingual('여러 계열사에 GHG 검증과 ISO를 제공하고 SK하이닉스 LCA 기회를 확대 중임.', 'Delivering GHG and ISO services across affiliates while expanding SK hynix LCA opportunities.'),
    nextQbrDate: '2026-08-28',
    opportunity: bilingual('SK하이닉스 LCA 및 반도체 제품 assurance, 계열사 GHG·ISO 확장', 'SK hynix LCA and Semiconductor Product Assurance; Affiliate GHG/ISO Expansion'),
    dealStage: bilingual('기존 수행 및 확장 논의', 'Existing delivery and expansion discussion'),
    risk: bilingual('계열사별 경쟁 상황과 확장 가능성을 별도로 관리해야 함.', 'Monitor competition and expansion potential affiliate by affiliate.'),
    growthStrategy: bilingual('SK하이닉스를 성장 Anchor로 삼아 그룹의 LCA·GHG·ISO 기회를 확대한다.', 'Use SK hynix as the growth anchor to expand LCA, GHG and ISO opportunities across the group.'),
    crossSell: bilingual('반도체 제품 LCA, PCF, Scope 3, 공급망 데이터 검증', 'Semiconductor product LCA, PCF, Scope 3 and supplier data assurance'),
    notes: bilingual('계열사별 관리가 필요한 그룹 Account', 'Group account requiring affiliate-by-affiliate management'),
    affiliates: [
      { id: 'sk-1', nameKo: 'SK하이닉스', nameEn: 'SK hynix', aliases: ['SK Hynix'] },
      { id: 'sk-2', nameKo: 'SK실트론', nameEn: 'SK siltron', aliases: ['SK Siltron'] },
      { id: 'sk-3', nameKo: 'SK이노베이션', nameEn: 'SK innovation', aliases: ['SK Innovation'] },
      { id: 'sk-4', nameKo: 'SK에너지', nameEn: 'SK energy', aliases: ['SK Energy'] },
      { id: 'sk-5', nameKo: 'SK E&S', nameEn: 'SK E&S', aliases: ['SK E and S'] },
    ],
  }),
  base({
    id: 'sam-hyosung', name: bilingual('효성그룹', 'Hyosung Group'), sector: bilingual('건설 및 제조', 'Construction & Manufacturing'),
    internalSponsor: bilingual('Ryan(라인 매니저), BGL(핵심 심사원)', 'Ryan (Line Manager); BGL (Key Auditor / Trusted Delivery Lead)'),
    clientSponsor: bilingual('홍수정, 주준석', 'Hong Su-jung; Joo Jun-seok'),
    qbrOutcome: bilingual('10년 이상 LCA 검증을 수행 중이며 K-ETS/GHG는 신규 개발 기회임.', 'Long-term LCA verification client; K-ETS/GHG remains a development opportunity.'),
    nextQbrDate: '2026-09-04',
    opportunity: bilingual('장기 LCA 검증 및 6~7개 계열사 K-ETS/GHG 검증', 'Long-Term LCA Verification and K-ETS/GHG Verification Across Affiliates'),
    dealStage: bilingual('LCA 수행, K-ETS/GHG 기회 개발', 'LCA delivery and K-ETS/GHG opportunity development'),
    dealValueUsd: 145000, dealValueNote: bilingual('LCA USD 100k + 추가 기회 USD 45k', 'USD 100k LCA revenue plus USD 45k development opportunity'),
    risk: bilingual('신뢰는 높지만 가격 민감도와 경쟁기관 압력을 모니터링해야 함.', 'Strong trust, but price sensitivity and competitor pressure require monitoring.'),
    growthStrategy: bilingual('LCA 매출을 방어하고 계열사 K-ETS/GHG 검증으로 확장한다.', 'Protect LCA revenue and expand into affiliate K-ETS/GHG verification.'),
    crossSell: bilingual('PCF, Scope 1/2/3 GHG assurance, 기후공시 및 맞춤 교육', 'PCF, Scope 1/2/3 GHG assurance, climate disclosure and customised training'),
    notes: bilingual('BGL의 수행 신뢰가 관계 유지의 핵심 자산', 'Trust in BGL delivery is a key retention asset'),
    affiliates: [
      { id: 'hyosung-1', nameKo: '효성티앤씨', nameEn: 'Hyosung TNC', aliases: [] },
      { id: 'hyosung-2', nameKo: '효성중공업', nameEn: 'Hyosung Heavy Industries', aliases: [] },
      { id: 'hyosung-3', nameKo: '효성첨단소재', nameEn: 'Hyosung Advanced Materials', aliases: [] },
      { id: 'hyosung-4', nameKo: '효성화학', nameEn: 'Hyosung Chemical', aliases: [] },
    ],
  }),
];
